dist: bionic

language: generic

install:

  # Install GNAT FSF
  - sudo apt-get -y install gnat gprbuild libxmlada-dom7-dev

  # Install xmllint for the tests
  - sudo apt-get -y install libxml2-utils

  # Install lcov for coverage
  - sudo apt-get -y install lcov

script:
  - ./configure --enable-coverage
  - make test
  - sh ./coverage.sh

after_success:
  - bash <(curl -s https://codecov.io/bash) -f are.cov
