site_name: Advanced Resource Embedder
docs_dir: docs
nav:
  - Introduction: index.md
  - Installation: Installation.md
  - Using ARE: Are_Using.md
  - Rules: Are_Installer.md
  - Generator: Are_Generator.md
theme: readthedocs
