description = "Advanced Resource Embedder Tests"
name = "are_tests"
version = "1.5.1"
authors = ["Stephane.Carrez@gmail.com"]
licenses = "Apache-2.0"
maintainers = ["Stephane.Carrez@gmail.com"]
maintainers-logins = ["stcarrez"]
project-files = ["../are_tests.gpr"]
tags = ["resource", "embedder", "generator"]
website = "https://gitlab.com/stcarrez/resource-embedder"
executables = ["are_harness"]

[[depends-on]]
are = "any"
utilada_unit = "^2.6.0"

[configuration]
disabled = true

[[pins]]
are = { path='..' }
